# files of NPC
NPC_SRC = $(NPC_HOME)/npc-sim/src
NPC_SRCS := $(shell find $(NPC_SRC) -name "*.cpp")
NPC_INC = $(NPC_HOME)/npc-sim/include

NPC_BUILD_DIR = $(NPC_HOME)/npc-sim/build
NPC_OBJS := $(addprefix $(NPC_BUILD_DIR)/, $(addsuffix .o, $(basename $(notdir $(NPC_SRCS)))))

# The archive of NPC
NPC_ARCHIVE = $(NPC_BUILD_DIR)/NPC.a
CXXFLAGS += -MMD -O3 $(shell sdl2-config --cflags)

$(NPC_BUILD_DIR)/%.o: $(NPC_SRC)/%.cpp
	@echo + CXX "->" NPC_HOME/$(shell realpath $< --relative-to $(NPC_HOME))
	@mkdir -p $(dir $@)
	@$(CXX) -I$(NPC_INC) $(CXXFLAGS) -c -o $@ $<

# Build the archive of NPC
$(NPC_ARCHIVE): $(NPC_OBJS)
	@echo + AR "->" $(shell realpath $@ --relative-to $(NPC_HOME))
	@ar rcs $(NPC_ARCHIVE) $(NPC_OBJS)

# Rule (`#include` dependencies): paste in `.d` files generated by gcc on `-MMD`
-include $(NPC_OBJS:.o=.d)

# Link flags for examples
LDFLAGS += $(shell sdl2-config --libs) -lSDL2_image -lSDL2_ttf

.PHONY: NPC-archive NPC-clean

NPC-archive: $(NPC_ARCHIVE)

NPC-clean:
	rm -rf $(NPC_BUILD_DIR)
